### ISSUE TITLE
Global Parameters are not being registered by `openmmtorch.TorchForce`

### ISSUE THREAD

**Issue by dominicrufa** [openmm/openmm-torch#30]
I attempted to retrieve the global parameter from a `openmmtorch.TorchForce`, but it doesnt seem to register any global parameters after they have been set. 
![image](https://user-images.githubusercontent.com/46943710/114450848-8304be00-9ba4-11eb-8e59-62e3bf04018a.png)
I modified the `openmm-ml` repo slightly [here](https://github.com/dominicrufa/openmm-ml) to put a `scale` term in the `forward` method of the `ANIForce` [here](https://github.com/dominicrufa/openmm-ml/blob/790f560d31211845f13b0b23d14fe940d8793d8a/openmmml/models/anipotential.py#L103)

**Comment by peastman** [comment]
This is related to how SWIG works.  Notice that it lists that force as just being a `Force` rather than a `TorchForce`.  There's a Python class for each C++ class.  `getForce()` somehow needs to figure out what Python class to use for each C++ Force object.  SWIG generates a "factory" to do that, but it only knows about the classes that are built into the main OpenMM library.  It doesn't know about ones defined in plugins, so it just returns an instance of the parent class, and that class doesn't have a `getNumGlobalParameters()` method.

We provide a static method you can use to cast it:

```python
force = TorchForce.cast(ml_system.getForce(5))
```

That gives you a `TorchForce` pointing to the same C++ object.

**Comment by dominicrufa** [comment]
alright, that did the trick. the (hopefully) last bit is that i am seeing this:
![image](https://user-images.githubusercontent.com/46943710/114467449-f06e1a00-9bb7-11eb-9d5a-a9e43d7f6c7d.png)
upon an attempt to retrieve the energy.
