### ISSUE TITLE
Versioning?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm-torch#55]
How are we planning to version openmm-torch, and for users to know which versions of openmm-torch match with OpenMM? 

Right now, OpenMM uses x.y.z for version numbers, but without true [semantic versioning](https://semver.org/), meaning API breaking changes can happen at `y` increments (e.g. 7.6.0 eliminated much of the Amoeba API and broke valid uses of the Python API). openmm-torch is using x.y, where we are just incrementing `y` for performance enhancement, bugfixes, etc.

How do we want to do versioning going forward, and is there any way to sensibly communicate which versions are intended to be compatible with which versions of OpenMM?

**Comment by raimis** [comment]
When the plugin is build, the OpenMM version is pinned to `x.y` and cannot be installed with a different version.

At the moment, the plugin supports only the latest OpenMM version (7.7), because of the CUDA context issue (#47, #49). In the future, we can build the plugin for several latest OpenMM versions, like we build for several PyTorch versions (1.8, 1.9, 1.10).

**Comment by jchodera** [comment]
Ah! These would be different variants in the conda-forge package build matrix then. Thanks, that makes sense!
